version: '3'

services:
    web:
        build: .
        command: python mange.py runserver 0.0.0.0:8000
        volumes:
            - .:/django1
        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
    celery:
    	build: .
    	command: celery -A django1 worker --loglevel=info
    	volumes:
    	    - .:/django1
    	depends_on:
    	    - db
    	    - redis
    db:
    	image: postgres:12
    	environment:
    	    POSTGRES_USER: postgres
    	    POSTGRES_PASSWORD: postgres
    	    POSTGRES_DB: postgres
    redis:
        image: redis:5
